import { COLORS } from './constants';

export const lightTheme = {
  dark: false,
  colors: {
    primary: COLORS.primary,
    primaryLight: COLORS.primaryLight,
    primaryDark: COLORS.primaryDark,
    accent: COLORS.accent,
    accentLight: COLORS.accentLight,
    background: '#FFFFFF',
    surface: '#F8F9FA',
    card: '#FFFFFF',
    text: COLORS.gray900,
    textSecondary: COLORS.gray600,
    textTertiary: COLORS.gray500,
    textInverse: COLORS.white,
    border: COLORS.gray200,
    borderLight: COLORS.gray100,
    notification: COLORS.error,
    success: COLORS.success,
    error: COLORS.error,
    warning: COLORS.warning,
    info: COLORS.info,
    star: COLORS.star,
    overlay: COLORS.overlay,
    skeleton: COLORS.gray200,
    inputBackground: COLORS.gray50,
    tabBar: '#FFFFFF',
    tabBarBorder: COLORS.gray200,
    statusBar: 'dark-content',
    headerBackground: '#FFFFFF',
    searchBar: COLORS.gray100,
  },
};

export const darkTheme = {
  dark: true,
  colors: {
    primary: '#66BB6A',
    primaryLight: '#81C784',
    primaryDark: '#388E3C',
    accent: '#FFB74D',
    accentLight: '#FFD54F',
    background: '#121212',
    surface: '#1E1E1E',
    card: '#252525',
    text: '#FAFAFA',
    textSecondary: '#B0B0B0',
    textTertiary: '#808080',
    textInverse: '#121212',
    border: '#333333',
    borderLight: '#2A2A2A',
    notification: '#EF5350',
    success: '#66BB6A',
    error: '#EF5350',
    warning: '#FFA726',
    info: '#42A5F5',
    star: '#FFD54F',
    overlay: 'rgba(0,0,0,0.7)',
    skeleton: '#333333',
    inputBackground: '#1E1E1E',
    tabBar: '#1E1E1E',
    tabBarBorder: '#333333',
    statusBar: 'light-content',
    headerBackground: '#1E1E1E',
    searchBar: '#2A2A2A',
  },
};

export default { lightTheme, darkTheme };
